### PR TITLE
recent loans on welcome page

### LINKED ISSUE #255: Implement Recent Loans
On the welcome page we have a mockup of recent loans.

We now have enough data to make a real list.

The real list will be the most recent loans, listing the item reference, the BatchNumber for the item, and the person that it was loaned to.

Note: for this, we will have to add `loanedDate` to `item` in `types.d.ts`.   This will be set in the `loan` method of DataProvider, and cleared  on `return` method of DataProvider.

Clicking on an item will go to the `ItemShow` for that item.  Clicking on the header will go to the `ItemList` page, filtered for items that are on loan.

Note: we'll have to add a new filter for `ItemList`, to filter for items that are on loan (`loanedTo` is non-null).

* [x] Add `On loan` filter to `ItemList`
* [x] Add `loanedDate` fields to `item` in `types.d.ts`
* [x] Produce real list of recent loans on welcome page.
* [ ] Implement `on-click` for recent loans
* [ ] Implement click for `Recent loans` header

### PR DESCRIPTION
**Pull request by TahaKhanAbdalli**
Fixes #255

### CODE REVIEW

**Comment by IanMayo** [comment]
Nice work. I see the `on loan` filter isn't quite working yet.

screencast

**Comment by TahaKhanAbdalli** [comment]
Actually I think there's an issue with the `ResetDateRangeFilter` because if I comment that lline of code, `onLoan` filter works fine.

**Comment by IanMayo** [comment]
> Actually I think there's an issue with the `ResetDateRangeFilter` because if I comment that lline of code, `onLoan` filter works fine.

Ok, let's comment out that line of code, please. We can then get this PR merged.

I'd like to ask Salony to resolve that. Could you create an issue to describe it please.

**Comment by IanMayo** [comment]
Thanks @TahaKhanAbdalli  Are you able to change it, so that clicking on `Recent loans` opens the `Items` tab with `On loan` selected?

**Comment by TahaKhanAbdalli** [comment]
Let me check.

> Thanks @TahaKhanAbdalli Are you able to change it, so that clicking on `Recent loans` opens the `Items` tab with `On loan` selected?

Let me check

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
