### PR TITLE
links removed for all columns except loanedTo on itemList

### LINKED ISSUE #488: Remove click on vault location from ItemList
From ItemList we can click on  vault location items.

This goes to vault location show/edit.

There is not a useful role for clicking on a vault location

For ItemList, remove `click` behaviour for all columns. All should just be plain text.  Aah, except for `Loaned to`.  It's right that this goes to the show page for that item.

### PR DESCRIPTION
**Pull request by TahaKhanAbdalli**
fixes #488

### CODE REVIEW

**Review by IanMayo — CHANGES_REQUESTED** [review]
Aah, I was hoping that `loanedTo` would clickable, but its not.   Maybe it never was.

Could you try to make `loanedTo` column clickable, to go to that `UserShow` please?

**Comment by IanMayo** [comment]
> > Aah, I was hoping that `loanedTo` would clickable, but its not. Maybe it never was.
> > Could you try to make `loanedTo` column clickable, to go to that `UserShow` please?
> 
> `loanedTo` is clickable. And it takes to `userShow` page. Could you check again, Please?

When I click on `Ian (d-1)`  in the page below, it just selects that row.

image

**Comment by TahaKhanAbdalli** [comment]
> > > Aah, I was hoping that `loanedTo` would clickable, but its not. Maybe it never was.
> > > Could you try to make `loanedTo` column clickable, to go to that `UserShow` please?
> > 
> > 
> > `loanedTo` is clickable. And it takes to `userShow` page. Could you check again, Please?
> 
> When I click on `Ian (d-1)` in the page below, it just selects that row.
> 
> image


https://github.com/DeepBlueCLtd/RCO/assets/50602678/43da46f5-4f74-4538-90f3-97c98fe3ccde

**Comment by IanMayo** [comment]
Sorry - don't know what I was doing wrong. Yes, it's working perfectly.

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
