### PR TITLE
removed db click functionality

### LINKED ISSUE #400: Alternate strategy to open show page
We've invested effort in supporting double-click to show for selectable lists.

But, in yesterday's trial ,two users were unaware that they could drill down to get more detail.  The `double-click` is a hidden behaviour.

So, I think we need an alternate strategy.  If a DataTable is selectable, we should show an `view` icon in a column to the right of the  select column.

The icon should _probably_ be the material `preview` icon.

I _don't think_ we will then need the double-click behaviour.

### PR DESCRIPTION
**Pull request by salony75way**
fixes #400

### CODE REVIEW

**Comment by IanMayo** [comment]
Can we have the icon on the far-left please?

**Comment by salony75way** [comment]
> Can we have the icon on the far-left column please?

@IanMayo Seems like its not possible to add new column before checkboxes 
 
Screenshot 2023-06-16 at 6 05 39 PM

**Comment by IanMayo** [comment]
Sorry - just to the right of the checkboxes.

**Review by IanMayo — CHANGES_REQUESTED** [review]
Sorry - just to the right of the checkboxes

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
