### PR TITLE
make start/end dates optional

### LINKED ISSUE #626: Item Start/End date should be optional
Start and End date for items are optional in the legacy data.  But in the Item Form they are mandatory.

We should relax the front-end to make start/end dates optional.

In our `item` type they are described as optional (`string | null`).

I know this will require a database update - I'll do that in Taha's branch this afternoon.  **Done**.

### PR DESCRIPTION
**Pull request by salony75way**
fixes #626

### CODE REVIEW

**Comment by IanMayo** [comment]
Dates are now optional. Thanks @salony75way  :-)

But, the finish date (when present) isn't being copied into the start date on `Save/Clone`.  This feature was added [here](https://github.com/DeepBlueCLtd/RCO/issues/541)

**Comment by salony75way** [comment]
> Dates are now optional. Thanks @salony75way :-)
> 
> But, the finish date (when present) isn't being copied into the start date on `Save/Clone`. This feature was added [here](https://github.com/DeepBlueCLtd/RCO/issues/541)

@IanMayo Seems like It's working on my end, Can you please share some test scenarios to replicate this?
 
https://github.com/DeepBlueCLtd/RCO/assets/45573884/035980e4-b60f-422f-876e-72a5cc69272c

**Comment by IanMayo** [comment]
Yes, @salony75way - yours seems ok.  Will re-test.

**Review by IanMayo — CHANGES_REQUESTED** [review]
The feature where we copy the finish date to the start date of the new item on `Save/Clone` doesn't work if only a date has been provided (no time elements).

**Comment by IanMayo** [comment]
Close. Superceded by #636

**Pull request closed without merging**
