### PR TITLE
single quote issue resolved

### LINKED ISSUE #1003: Single quote in text field throws error
If we try an give a user the name `Rory O'Brien` we get a SQL error.

We need to be able to use this character in names and addresses.

Once we know what substitution we need to make, we should probably produce a `sanitise text` method.

Note: this _may_ be a `soul-cli` issue.

### LINKED ISSUE #1005: Address accepts a quote on `Create` but not on `Edit`
I can `create` a new address that contains a `'` character: `22 Dumb'rain street`

But, if I edit then save that address `soul` throws an error:
image

Note: I get the same issue for items.  I can include a `'` in the `consec` for an item being added to a batch, but If I subsequently edit that item, it will not save.

### LINKED ISSUE #1006: Including a `'` in free text search throws error
The search functionality throws an error if we include `'` in the free text search.

This is a character that can legitimately occur in names and addresses, so it should be allowable.

### PR DESCRIPTION
**Pull request by TahaKhanAbdalli**
fixes #1006 
Fixes #1003 
Fixes #1005

### CODE REVIEW

**Comment by TahaKhanAbdalli** [comment]
Issues #1005 and #1002 are also addressed in this same PR.

**Comment by IanMayo** [comment]
Thanks @TahaKhanAbdalli . But, do we need to swap the two quotes for one when data comes back from `Soul`?

(build not complete yet - so I can't test it myself)

**Comment by TahaKhanAbdalli** [comment]
> swap
No, There is no need to swap two quotes for one.

**Comment by IanMayo** [comment]
A couple of linter issues, please @TahaKhanAbdalli 
image

**Comment by IanMayo** [comment]
> No, There is no need to swap two quotes for one.

I can see that we don't need to _Fix_ the two quotes, and that data renders ok.  Can you explain why we haven't had to do that?

**Review by IanMayo — APPROVED** [review]
Tested and working.

**Comment by IanMayo** [comment]
Hello @TahaKhanAbdalli - I've tagged this with the 3 issues that I think it fixes. Would you mind double-checking please?

image

**Pull request merged**
