### PR TITLE
Added url params to login

### LINKED ISSUE #174: URL param to login (temporarily)
It would be good to distribute a URL that allowed RCO to open, already logged in as a user.

This _could_ also be useful for E2E testing, if/when we have that.

### PR DESCRIPTION
**Pull request by TahaKhanAbdalli**
Fixes #174

### CODE REVIEW

**Comment by IanMayo** [comment]
Thanks Taha, it works - but we get this warning.  Can you work out why it is displayed, and fix it please?
image

**Comment by TahaKhanAbdalli** [comment]
This is by default being shown by react admin because react admin checks the authentication before mounting the component. I can add the delay until the toaster disappears but that will not be a good user experience.

**Comment by IanMayo** [comment]
Hmm, is it an option to put the logic somewhere else?  Maybe in `app.tsx`?

**Comment by TahaKhanAbdalli** [comment]
There is a trade off. I would have to show the notification of wrong password or any error manually (using material UI) rather than using `useNotify` of react admin.

**Comment by IanMayo** [comment]
I'm afraid I won't understand the difference until I see a working implementation.

Could you have a go at putting it in `app.tsx` please?

**Comment by TahaKhanAbdalli** [comment]
Pushed.

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
