### PR TITLE
reference data edit and create implemented

### PR DESCRIPTION
**Pull request by TahaKhanAbdalli**

### CODE REVIEW

**Comment by IanMayo** [comment]
Can we go straight to `Edit` please?   The `Show` form is a step in the process that doesn't bring any value.

**Comment by TahaKhanAbdalli** [comment]
Should I completely remove the show page?

**Comment by IanMayo** [comment]
> Should I completely remove the show page?

Yes please.  The `list` shows the same data as `show`.  We just need `edit` and `create` (which can prob use the same form :-) ).

**Comment by IanMayo** [comment]
@TahaKhanAbdalli -  there's something that `Codacy` doesn't like, too:
image

**Review by IanMayo — APPROVED** [review]
Great, thanks.

**Pull request merged**
