### PR TITLE
promote buttons to left side

### LINKED ISSUE #491: Promote buttons on right-hand side to left-hand side
buttons for selected items are shown on the right-hand side.

See if they can be moved to left-hand side.   Maybe use color to make them more visible.

Also the "Asse Repprt". "Add filter", "Columns" buttons are getting missed.  Maybe try to move them left aswell.

### PR DESCRIPTION
**Pull request by salony75way**
fixes #491

### CODE REVIEW

**Comment by IanMayo** [comment]
Can you explain how `columnsFit` works please?

It _seems_ a bit hit & miss.

**Comment by salony75way** [comment]
> Can you explain how `columnsFit` works please?
> 
> It _seems_ a bit hit & miss.

@IanMayo In `columnsFit` we are passing default numbers of columns (listed without scrollbar) then checking if selected columns length is max from `columnsFit` then we will align actions to left otherwise it will show to right(as it is).

**Comment by IanMayo** [comment]
I've had a play with this @salony75way - but it is still possible for action-buttons to disappear off to the right of the screen.

I'm not a my normal PC right now, so can't record a video for you.  Maybe later.

But, I think it's worth us considering an alternate strategy, please.

**Comment by salony75way** [comment]
> I've had a play with this @salony75way - but it is still possible for action-buttons to disappear off to the right of the screen.
> 
> I'm not a my normal PC right now, so can't record a video for you. Maybe later.
> 
> But, I think it's worth us considering an alternate strategy, please.

@IanMayo I will check and test this on different screen sizes and find alternate strategy, Thanks!

**Comment by IanMayo** [comment]
This still isn't great for me @salony75way   Can we have them permanently on the left-hand side?
screencast

**Comment by IanMayo** [comment]
Let's go permanently to the left, please.

(until they change their mind ;-) )

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
