### PR TITLE
rich item view implemented

### LINKED ISSUE #389: Allow `item` search by `platform` and `project`
Platform and Project are fields in the batch.

But, frequently users will want to find items from a particular platform or project.

We _could_ pull these fields through in the backend.  Would it be very difficult to add them to `ItemList` in the front-end?  Does react-admin support that?

@salony75way said:
> Seems like react-admin doesn't support nested references so for this type of filter we need to create a custom component.

Note: we'll support this in the future by using a VIEW to collate project and platform into the item

### Strategy

* [ ] Introduce `richItem` view that adds `platformId` and `projectId` from `Batches` table
* [ ] Connect `ItemList` to `richItem`, not `item`
* [ ] Extend front-end to introduce `Platform` and `Project` columns for `ItemList`
* [ ] Introduce `Platform` and `Project` filters for `ItemList`

Note: this issue is blocked by this one: https://github.com/DeepBlueCLtd/RCO_Legacy/issues/33

Note 2: I don't _fully_ understand how we're going to do this.  I know react-admin likes each access to a specific resource to be in the same format - without columns changing.  But, this new view will have a slightly different shape.  _maybe_ we have to introduce `constants.R_RICH_ITEM` - and `ItemList` always runs from that.  _Maybe_...

**Update:**  `richItem` view added to RCO2.sqlite

### PR DESCRIPTION
**Pull request by TahaKhanAbdalli**
fixes #389

### CODE REVIEW

**Comment by TahaKhanAbdalli** [comment]
@IanMayo still need to fix synchronization of `item` and `richItem` on `MOCK` server

**Comment by IanMayo** [comment]
Thanks Taha, but I _think_ that RICH_ITEMS should only be referred to when declaring the `Live Items` and `All items` listings.  I'm pretty sure the others should just refer to `ITEMS`.

**Comment by TahaKhanAbdalli** [comment]
> Thanks Taha, but I _think_ that RICH_ITEMS should only be referred to when declaring the `Live Items` and `All items` listings. I'm pretty sure the others should just refer to `ITEMS`.

On some instances, we need to navigate to `richItem` and for `Edit` and `Create` we need to explicitly tell that we are referrring to `Item` resource because by default react-admin refers to the resource using `url`

**Review by IanMayo — APPROVED** [review]
tested and working

**Pull request merged**
