### PR TITLE
cannot create new user issue resolved

### LINKED ISSUE #1004: Cannot create new user
When I try to create a new user, I get this error:
image

I've had a quick look at the code, but can't see where the `active` field is being generated.  Note: while we have `active` for other resource types, for users this concept is managed via the `departureDate`

### PR DESCRIPTION
**Pull request by TahaKhanAbdalli**
fixes #1004

### CODE REVIEW

**Comment by IanMayo** [comment]
Thanks @TahaKhanAbdalli - do you understand where the issue came from?  I'm inquisitive about where the `active` field came from.

**Comment by TahaKhanAbdalli** [comment]
The problem was with the exporting object from the `user/index.tsx` file. This object manages routes, but I forgot to include the create function in it. As a result, it was redirecting to the `reference data` create form by mistake.

**Comment by IanMayo** [comment]
Thanks @TahaKhanAbdalli 

I should have noticed we were looking at the wrong form, duh!

Are you able to give the date a default value of 10 years in the future?

**Comment by TahaKhanAbdalli** [comment]
If the date you mentioned is `departedDate` it's already 10 years in the future.

**Comment by IanMayo** [comment]
> If the date you mentioned is `departedDate` it's already 10 years in the future.

Yes, `departedDate`. I just have an empty date field:
image

**Comment by TahaKhanAbdalli** [comment]
Oky, Let me check.

**Comment by TahaKhanAbdalli** [comment]
> > If the date you mentioned is `departedDate` it's already 10 years in the future.
> 
> Yes, `departedDate`. I just have an empty date field: image

Done

**Review by IanMayo — APPROVED** [review]
Tested and working

**Pull request merged**
