### PR TITLE
project column fixed on item list and batch list pages

### LINKED ISSUE #778: `Project` column missing from `Live Items`
We have a `Project` filter for Live Items, but we can't request that the `Project` column be shown:

image

Note: we have to pull the label for `Project` from the config data.

### PR DESCRIPTION
**Pull request by TahaKhanAbdalli**
fixes #778

### CODE REVIEW

**Comment by IanMayo** [comment]
Hmm, this is working for me:
image

**Comment by TahaKhanAbdalli** [comment]
Is this working? For updation to work, you'll also need to clear local storage

**Comment by IanMayo** [comment]
It's working on the Heroku deployment: https://rco-review-pr-780.herokuapp.com/#/batch

I haven't opened that URL before, so nothing was cached.

**Comment by TahaKhanAbdalli** [comment]
> It's working on the Heroku deployment: https://rco-review-pr-780.herokuapp.com/#/batch
> 
> I haven't opened that URL before, so nothing was cached.

Ok then. We can merge this PR.

**Review by IanMayo — APPROVED** [review]
Tested and working.

**Pull request merged**
