### PR TITLE
customized item lists Batch and User

### LINKED ISSUE #390: Custom `ItemList` when embedded
We have an `ItemList` in `UserShow` that lists the items on loan by that user.  We also embed `ItemList` in other `Show` components.

We may have chosen columns in the main `ItemList` to do a job, but when there are lots, it makes `UserShow` wider than it needs to be.  

So, the `ItemList` in `UserShow` should just show these columns:
- Reference
- Media type
- Protective Marking
- Remarks

The `ItemList` in `BatchShow` should just show these columns:
- Reference
- Media type
- Protective Marking
- Remarks
- Loaned to
- Destruction: (Destruction + (DestructionDate ?? 'Pending')))
- Dispatch: (Dispatch + (DispatchDate ?? 'Pending')))

(it appears that the `ItemList`s in Dispatches and Destructions already have custom columns.

### PR DESCRIPTION
**Pull request by TahaKhanAbdalli**
Fixes #390

### CODE REVIEW

**Comment by IanMayo** [comment]
Thanks. But, it's the item reference we should show, not the batch reference:
image

**Comment by IanMayo** [comment]
@TahaKhanAbdalli  - there is some issue with `Live Items`:
cast

**Comment by TahaKhanAbdalli** [comment]
Working fine on my side. Maybe you need to clear cache

**Comment by IanMayo** [comment]
> Working fine on my side. Maybe you need to clear cache

Aah, I _think_ it's when you have RCO open in two browser tabs.  I _think_ they overwrite each other's cookie.

**Comment by IanMayo** [comment]
could you fix the conflicts please @TahaKhanAbdalli ?

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
